### ISSUE TITLE
`dry_run_handler` needs to have a flexible output

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/climate-explorer-data-prep#135]
We should style the [`dry_run_handler`](https://github.com/pacificclimate/climate-explorer-data-prep/blob/master/dp/generate_climos.py#L72) after the [`dry_run`](https://github.com/pacificclimate/climate-explorer-data-prep/blob/master/dp/generate_prsn.py#L22) method from `generate_prsn`. This style would give us more flexibility when using the method in `thunderbird`.

**Comment by sum1lim** [comment]
The issue lost its necessity after a better strategy has been discovered, thus closing the issue.
