### ISSUE TITLE
Degree day annual data should be the sum of degree day seasonal data

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-data-prep#57]
I generated degree data climatologies, but I think the usual climatology approach where an annual value is the _mean_ of the seasonal value is meaningless for an accumulative value like degree days. I think we want annual values to be the _sum_ of seasonal values. I need to update `generate_climos` and redo that data.

**Comment by rod-glover** [comment]
Can you give me an idea of what `generate_climos` is supposed to do here? What are the inputs and what are the outputs?

**Comment by corviday** [comment]
The input would be degree days data of seasonal resolution. The output would be degree day climatologies of seasonal and annual resolution. 

The issue lies with what "annual degree days" means: I believe it should be the _sum_ of seasonal degree days, not their mean.

**Comment by rod-glover** [comment]
OK. I agree with your interpretation; I'd be _extremely_ surprised if annual degree days was anything else.

**Comment by rod-glover** [comment]
Let's also discuss what climatological coding to use in the `frequency` attribute. Here's my take on it:

- The final product is climatological _means_ of degree day values for seasons and annually.
- An intermediate product between climo mean of annual degree days, computed from seasonal degree days, is annual degree days, which are indeed the sum of seasonal degree days for that year (with caution about what constitutes a "year"; the seasons cross year boundaries).
- The final annual product is the climo mean of these intermediate annual degree day datasets.
- Therefore the final products should have `frequency` values of `sClimMean` and `aClimMean`.
- If we preserve the intermediate annual degree day datasets (which easily might have value), then we need to code these appropriately too. However, they are not climatological datasets, and so their `frequency` value cannot be an `xClimOp` value, which implies climatology. In fact they are plain vanilla datasets as far as `frequency` is concerned, and their code should be `yr`. (See [PCIC Metadata Std;](https://pcic.uvic.ca/confluence/display/CSG/PCIC+metadata+standard+for+downscaled+data+and+hydrology+modelling+data#PCICmetadatastandardfordownscaleddataandhydrologymodellingdata-MIPtable/table_id/frequency) I'll shortly be extending this for explicit mean and for standard deviation.)
