### ISSUE TITLE
Frost Days - missing?

### ISSUE THREAD

**Issue by tqmurdock** [pacificclimate/climate-explorer-data-prep#79]
I don't seem to be able to find the frost days variable. There's freezing degree days but that isn't the same thing. FD counts the # of days below freezing.

**Comment by corviday** [comment]
Should be straightforward to add them, since they were calculated for the plan2adapt update.

**Comment by corviday** [comment]
![Screenshot from 2019-07-29 08-51-00](https://user-images.githubusercontent.com/4512605/62062556-12561c00-b1de-11e9-884d-e0fba246cf16.png)

Frost Days is now available in Climate Explorer (for BC, at least, we don't have the all-Canada data, unlike the other ETCCDI indicators). It lacks a description - see dropdown variable menu. @tqmurdock, what should the description be?

**Comment by corviday** [comment]
Have updated the `long_name` for `fdETCCDI` to `Frost Days`. Frost day data is now available.

![frostdropdown](https://user-images.githubusercontent.com/4512605/62154550-c9749500-b2bb-11e9-95de-edd0425de5a3.png)
