### ISSUE TITLE
Ensembles of Degree Day Data

### ISSUE THREAD

**Issue by tqmurdock** [pacificclimate/climate-explorer-data-prep#80]
It looks like the PCIC12 is only available for T & P right now. 

We just had a question from a user about comparing Cooling Degree Days on the explorer to other tools and getting different values (partly because the other tools do a bad job of showing change from baseline, which we do a better job of, but CDD only shows up for individual models). 

Is the PCIC12 for climdex indices in process and do we have an ETA for, or is there a stumbling block for computing it?

**Comment by corviday** [comment]
I've started working on this, but have run into an issue: we can't generate the 2070-2099 HadGEM2-ES climatologies. Some of the HadGEM2-ES datasets end with October 1, 2099, but our climatology generation [would require them to end at or after December 30, 2100](https://github.com/pacificclimate/nchelpers/blob/master/nchelpers/__init__.py#L155) to generate the 2070-2099 climatology.

**Comment by tqmurdock** [comment]
I think it's a good thing that the process fails rather than ignore missing data in general, so that we know about it.... if they are truly missing you can run the climatologies in this case just ignore the missing values that will be fine

However, I'm skeptical that they are really missing because this is the model that only has 360 days in a year. Are you sure that the end of the record is missing and it's not just the unconventional days per year causing an issue? 

Note that there are also models that treat leap years differently.

**Comment by corviday** [comment]
The 360 day calendar was my first thought too, I've been burned before. :) 

But in this case I'm starting with a seasonal resolution dataset, four timestamps per year, so the 360 day calendar doesn't really matter at this step. Here's an example dataset:

```
netcdf cdd_seasonal_HadGEM2-ES_rcp85_r1i1p1_1951-2100 {
dimensions:
	lon = 313 ;
	lat = 145 ;
	time = UNLIMITED ; // (596 currently)
variables:
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
		lon:axis = "X" ;
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
		lat:axis = "Y" ;
	double time(time) ;
		time:units = "days since 1950-01-01 00:00:00" ;
		time:long_name = "Time" ;
		time:calendar = "360_day" ;
		time:standard_name = "Time" ;
	float cdd(time, lat, lon) ;
		cdd:units = "degree days" ;
		cdd:_FillValue = -32768. ;
		cdd:standard_name = "CDD" ;
		cdd:long_name = "CDD" ;

}
```

This dataset has 596 timestamps. January 1, 1951 (Winter), April 1 1951 (Spring), July 1 1951 (Summer), October 1 1951 (Autumn), etc. The last, 596th timestep is October 1 2099.

If we had the data point at January 1 2100, it would have the data for December 2099, January 2100, and February 2100.

**Comment by tqmurdock** [comment]
Ok if you're sure it's a missing data issue I think it's fine to just ignore the missing values - it won't change the average much to have 29 years instead of 30 in the last 3 months of the year for this one model. 

But it's curious.

**Comment by corviday** [comment]
PCIC12 degree day data is now available in PCEX.
