### ISSUE TITLE
generate_climos should update the history metadata attribute

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-data-prep#82]
I have receently been trying to figure out which file a suspicious climatology was made from; it would be nice if generate_climos updated the `history` attribute with the command used to run it, similar to the way `cdo` does.

**Comment by corviday** [comment]
Or maybe some other, new, optional attribute.

**Comment by rod-glover** [comment]
Off the top, I think updating `history` is probably best. That's what it's for, and I think it would be best to avoid introducing anything unnecessary and non-standard unless we have to. Not updating `history` was a failing of the original code that I never quite got around to fixing, or even creating an issue for. Now, voila.

**Comment by jameshiebert** [comment]
If we can recommend some specific as to what entries to add to the `history` attribute, this would make a `good-first-issue` for incoming developers.

**Comment by corviday** [comment]
I don't think we have a formal standard for this, but I write scripts to make a `cdo`-style update to `history` of the general form `datetime: tool-name arguments\n` at the top of the `history` attribute, retaining all older entries.

[Here's a recent one from the Frost Free Day script](https://github.com/pacificclimate/data-prep-actions/blob/51495d444d57e258f900d5aaf17b70b3a868e1e2/actions/frost_free_days/frost_free_days.py#L51-L52).

**Comment by sum1lim** [comment]
I figured that `generate_climos` actually updates the history attribute.
For example, the history attribute of `tiny_daily_pr.nc` is:
```
		:history = "Thu Mar 21 14:49:01 2019: cdo sellonlatbox,216.5625,219.375,40.4636506825932,48.8352434707287 /storage/data/climate/downscale/BCCAQ2/CMIP5/CanESM2/pr_day_CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc /storage/home/nrados/tiny_daily_pr.nc\n",
			"Thu Sep  1 14:34:03 2016: ncrcat -O /storage/data/climate/downscale/BCCAQ2/CMIP5/timetmp/time_subset_pr_day_CanESM2_historical_r1i1p1_19500101-20051231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/timetmp/time_subset_pr_day_CanESM2_rcp26_r1i1p1_20060101-21001231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/CanESM2/pr_day_CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc\n",
			"Thu Sep 01 14:33:15 2016: cdo -O seldate,1950-01-01T00:00,2005-12-31T23:59 /storage/data/climate/downscale/BCCAQ2/CMIP5/spacetmp/space_subset_pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/timetmp/time_subset_pr_day_CanESM2_historical_r1i1p1_19500101-20051231.nc\n",
			"Thu Sep  1 14:32:42 2016: ncks -O -d lon,215.,310. -d lat,40.,85. /storage/data/climate/downscale/BCCAQ2/CMIP5/grouptmp/pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/spacetmp/space_subset_pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc\n",
			"2011-04-13T23:04:41Z CMOR rewrote data to comply with CF standards and CMIP5 requirements." ;
```

Running `generate_climos` on this file creates these output files:
```
pr_aClimMean_CanESM2_historical_r1i1p1_19610101-19901231.nc
pr_aClimMean_CanESM2_historical_r1i1p1_19710101-20001231.nc
pr_aClimMean_CanESM2_historical_r1i1p1_19810101-20101231.nc
pr_aClimMean_CanESM2_historical_r1i1p1_20100101-20391231.nc
pr_aClimMean_CanESM2_historical_r1i1p1_20400101-20691231.nc
pr_aClimMean_CanESM2_historical_r1i1p1_20700101-20991231.nc
pr_mClimMean_CanESM2_historical_r1i1p1_19610101-19901231.nc
pr_mClimMean_CanESM2_historical_r1i1p1_19710101-20001231.nc
pr_mClimMean_CanESM2_historical_r1i1p1_19810101-20101231.nc
pr_mClimMean_CanESM2_historical_r1i1p1_20100101-20391231.nc
pr_mClimMean_CanESM2_historical_r1i1p1_20400101-20691231.nc
pr_mClimMean_CanESM2_historical_r1i1p1_20700101-20991231.nc
pr_sClimMean_CanESM2_historical_r1i1p1_19610101-19901231.nc
pr_sClimMean_CanESM2_historical_r1i1p1_19710101-20001231.nc
pr_sClimMean_CanESM2_historical_r1i1p1_19810101-20101231.nc
pr_sClimMean_CanESM2_historical_r1i1p1_20100101-20391231.nc
pr_sClimMean_CanESM2_historical_r1i1p1_20400101-20691231.nc
pr_sClimMean_CanESM2_historical_r1i1p1_20700101-20991231.nc
```

History attribute of `pr_aClimMean_CanESM2_historical_r1i1p1_19610101-19901231.nc` is:
```
		:history = "Thu May 21 11:12:05 2020: cdo -O -replace /tmp/cdoPy6pyrutd4 /tmp/cdoPyox1r7abo /tmp/cdoPyr4x7uz_r\n",
			"Thu May 21 11:12:04 2020: cdo -O -timmean /tmp/cdoPyrbkdk6en /tmp/cdoPy6pyrutd4\n",
			"Thu May 21 11:12:04 2020: cdo -O -seldate,1961-01-01,1990-12-31 ../tests/data/tiny_daily_pr.nc /tmp/cdoPyrbkdk6en\n",
			"Thu Mar 21 14:49:01 2019: cdo sellonlatbox,216.5625,219.375,40.4636506825932,48.8352434707287 /storage/data/climate/downscale/BCCAQ2/CMIP5/CanESM2/pr_day_CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc /storage/home/nrados/tiny_daily_pr.nc\n",
			"Thu Sep  1 14:34:03 2016: ncrcat -O /storage/data/climate/downscale/BCCAQ2/CMIP5/timetmp/time_subset_pr_day_CanESM2_historical_r1i1p1_19500101-20051231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/timetmp/time_subset_pr_day_CanESM2_rcp26_r1i1p1_20060101-21001231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/CanESM2/pr_day_CanESM2_historical+rcp26_r1i1p1_19500101-21001231.nc\n",
			"Thu Sep 01 14:33:15 2016: cdo -O seldate,1950-01-01T00:00,2005-12-31T23:59 /storage/data/climate/downscale/BCCAQ2/CMIP5/spacetmp/space_subset_pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/timetmp/time_subset_pr_day_CanESM2_historical_r1i1p1_19500101-20051231.nc\n",
			"Thu Sep  1 14:32:42 2016: ncks -O -d lon,215.,310. -d lat,40.,85. /storage/data/climate/downscale/BCCAQ2/CMIP5/grouptmp/pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc /storage/data/climate/downscale/BCCAQ2/CMIP5/spacetmp/space_subset_pr_day_CanESM2_historical_r1i1p1_18500101-20051231.nc\n",
			"2011-04-13T23:04:41Z CMOR rewrote data to comply with CF standards and CMIP5 requirements." ;
```
It shows that there have been updates on `Thu May 21 11:12:04`(the date and time I ran `generate_climos`).
Therefore, I believe this issue can be closed, but before that, I want to hear opinions from anyone who thinks there was a mistake on my test run OR `generate_climos` still needs improvement on history attribute updating behavior.

**Comment by jameshiebert** [comment]
@corviday correct me if I'm wrong, but I think the operative phrase in your issue description is: "with the command used to run it". @sum1lim what you've found is that a run of `generate_climos` is composed of multiple runs of `cdo`, each which add their history entry. Possibly what Lee thought would be useful is the full command line listing of everything that the [`generate_climos` script](with the command used to run it) is called with?

**Comment by corviday** [comment]
Apologies, I seem to have made this issue in error. At the time, I was looking at some confusing data that didn't seem to have any updates to `history` from the climatology-generating process (or indeed, any `history` at all), but it appears that `generate_climos` does, by default, do them by way of `cdo`. I don't know if the data I was looking at had its `history` erased as a result of a later process or was made with `export CDO_RESET_HISTORY=1` in the environment or what, but it doesn't seem to be a general problem the way I assumed it was.

However, @jameshiebert has a good point. The exact `cdo` commands run vary by what kind of data the input is, and it might not always be obvious to someone tracing data provenance that a collection of 2-4 `cdo` commands represents a use of `generate_climos` run. It might be useful to have an entry in history indicating that `generate_climos` was run, and some details about how.
