### ISSUE TITLE
Remove unnecessary datasets from plan2adapt

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-data-prep#90]
The plan2adapt data ensemble was originally created by cloning PCEX's data ensemble, but most of those files are unneeded by plan2adapt, and [may be slowing it down](https://github.com/pacificclimate/p2a-rule-engine/issues/3). 

Remove unnecessary files from the ensemble, while testing to see if the rules engine runs any more quickly.

**Comment by corviday** [comment]
@nikola-rados says:

> translate_variable = translate_names({
>         'temp': ['tasmin', 'tasmax'],
>         'prec': ['pr'],
>         'dg05': ['gdd'],
>         'nffd': ['fdETCCDI'],
>         'pass': ['prsn'],
>         'dl18': ['hdd']
> })
> '''Given a variable component, translate it to the CE equivalent'''

yields 7 variables plan2adapt actually uses, out of 45 variables present in the ensemble. Most of the unused variables have only a few datasets, but removing them seems like a good start.

```sql
SELECT data_file_variables.netcdf_variable_name, COUNT(data_file_variables.netcdf_variable_name)
FROM 
  ce_meta.ensembles, 
  ce_meta.ensemble_data_file_variables, 
  ce_meta.data_file_variables, 
  ce_meta.variable_aliases
WHERE 
  ensembles.ensemble_id = ensemble_data_file_variables.ensemble_id AND
  ensemble_data_file_variables.data_file_variable_id = data_file_variables.data_file_variable_id AND
  data_file_variables.variable_alias_id = variable_aliases.variable_alias_id AND
  ensembles.ensemble_name = 'p2a_files'
GROUP BY (netcdf_variable_name)
ORDER BY netcdf_variable_name;
```

| variable_name | count |
|---------------|-------|
| altcddETCCDI  | 16    |
| altcsdiETCCDI | 16    |
| altcwdETCCDI  | 16    |
| altwsdiETCCDI | 16    |
| cdd           | 282   |
| cddETCCDI     | 16    |
| csdiETCCDI    | 16    |
| cwdETCCDI     | 16    |
| fdd           | 282   |
| fdETCCDI      | 423   |
| gdd           | 286   |
| gslETCCDI     | 16    |
| hdd           | 282   |
| idETCCDI      | 16    |
| pr            | 1044  |
| prcptotETCCDI | 16    |
| prsn          | 1530  |
| r10mmETCCDI   | 16    |
| r1mmETCCDI    | 16    |
| r20mmETCCDI   | 16    |
| r95pETCCDI    | 16    |
| r99pETCCDI    | 16    |
| rp20pr        | 48    |
| rp20tasmax    | 46    |
| rp20tasmin    | 48    |
| rp50pr        | 46    |
| rp5pr         | 47    |
| rp5tasmax     | 47    |
| rp5tasmin     | 47    |
| rx1dayETCCDI  | 16    |
| rx5dayETCCDI  | 16    |
| sdiiETCCDI    | 16    |
| suETCCDI      | 16    |
| tasmax        | 1056  |
| tasmin        | 1038  |
| tn10pETCCDI   | 16    |
| tn90pETCCDI   | 16    |
| tnnETCCDI     | 16    |
| tnxETCCDI     | 16    |
| trETCCDI      | 16    |
| tx10pETCCDI   | 16    |
| tx90pETCCDI   | 16    |
| txnETCCDI     | 16    |
| txxETCCDI     | 16    |
| wsdiETCCDI    | 16    |

**Comment by corviday** [comment]
- [ ] remove unused variables
- [ ] remove unused emissions scenarios (if any)
- [ ]  remove unused models (if any)

**Comment by nikola-rados** [comment]
If you are looking for models used there is a [method](https://github.com/pacificclimate/p2a-rule-engine/blob/master/p2a_impacts/fetch_data.py#L120) that handles which get selected.  Here is a snippet:
```python
def get_models(sesh, hist_var, ensemble):
    """Return a list of models needed to compute the percentile"""
    historical_baseline = 'anusplin'
    if hist_var == 'hist':
        return [historical_baseline]
    else:
        # return all models EXCEPT for the historical baseline
        all_models = models(sesh, ensemble_name=ensemble)
        all_models.remove(historical_baseline)
        return all_models
```

**Comment by corviday** [comment]
I made an ensemble called `p2a_rcp85` that contains all datafiles that satisfy either this query (ANUSPLIN historical data):

```sql
SELECT 
  data_files.filename
FROM 
  ce_meta.ensembles, 
  ce_meta.ensemble_data_file_variables, 
  ce_meta.data_file_variables, 
  ce_meta.data_files, 
  ce_meta.runs, 
  ce_meta.models
WHERE 
  ensembles.ensemble_id = ensemble_data_file_variables.ensemble_id AND
  ensemble_data_file_variables.data_file_variable_id = data_file_variables.data_file_variable_id AND
  data_file_variables.data_file_id = data_files.data_file_id AND
  data_files.run_id = runs.run_id AND
  runs.model_id = models.model_id AND
  ensembles.ensemble_name = 'p2a_files' AND 
  models.model_short_name = 'anusplin';
```

or this one (PCIC12 model output for required variables):
```
SELECT 
  data_files.filename
FROM 
  ce_meta.ensembles, 
  ce_meta.ensemble_data_file_variables, 
  ce_meta.data_file_variables, 
  ce_meta.data_files, 
  ce_meta.models, 
  ce_meta.runs, 
  ce_meta.emissions, 
  ce_meta.time_sets
WHERE 
  ensembles.ensemble_id = ensemble_data_file_variables.ensemble_id AND
  ensemble_data_file_variables.data_file_variable_id = data_file_variables.data_file_variable_id AND
  data_file_variables.data_file_id = data_files.data_file_id AND
  data_files.run_id = runs.run_id AND
  data_files.time_set_id = time_sets.time_set_id AND
  runs.model_id = models.model_id AND
  runs.emission_id = emissions.emission_id AND
  ensembles.ensemble_name = 'p2a_files' AND 
  emissions.emission_short_name LIKE '%rcp85' AND 
  data_file_variables.netcdf_variable_name IN ('tasmax', 'tasmin', 'prsn', 'pr', 'gdd', 'fdETCCDI', 'hdd') AND 
  models.model_short_name IN ('ACCESS1-0', 'CanESM2', 'CCSM4', 'CNRM-CM5', 'CSIRO-Mk3-6-0', 'GFDL-ESM2G', 'HadGEM2-CC', 'HadGEM2-ES', 'inmcm4', 'MIROC5', 'MPI-ESM-LR', 'MRI-CGCM3', 'PCIC12' ) AND 
  time_sets.start_date > '2000-01-01';
```

resulting in a dataset of 764 files, compared to the current size of `p2a_files` of 7016.

In an informal test run on my workstation, executing the rules engine with the new ensemble took 18 minutes, while the old ensemble took 57. Promising! Needs a test less likely to be interrupted by random background processes.

**Comment by corviday** [comment]
Similar results on leopard. Old ensemble:
```
real	31m52.355s
user	27m8.774s
sys	0m25.228s
```

New ensemble:
```
real	10m3.289s
user	7m56.647s
sys	0m9.817s
```

**Comment by nikola-rados** [comment]
Nice job @corviday! What parameters did you run the script with?

**Comment by corviday** [comment]
```bash
(venv) [lzeman@leopard p2a-rule-engine]$ time python scripts/process.py -c data/rules.csv -r vancouver_island -e p2a_rcp85
```

**Comment by nikola-rados** [comment]
Hmm, ok so that is still using `vancouver_island`.  I'm curious to see what the run times would look like for `bc`.  Would you be able to run the tests again using that parameter?

**Comment by corviday** [comment]
```bash
(venv) [lzeman@leopard p2a-rule-engine]$ time python scripts/process.py -c data/rules.csv -r bc -e p2a_rcp85 

real	9m22.079s
user	8m0.230s
sys	0m8.937s

(venv) [lzeman@leopard p2a-rule-engine]$ time python scripts/process.py -c data/rules.csv -r bc -e p2a_files

real	31m20.965s
user	27m19.579s
sys	0m24.963s
```bash

**Comment by nikola-rados** [comment]
Thanks for running that.  I thought it would be faster but the difference is negligible.

**Comment by corviday** [comment]
- [ ] Find out whether we need rcp26 and rcp45 too
