### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/climate-explorer-data-prep#93]
In order for [`thunderbird`](https://github.com/pacificclimate/thunderbird) to wrap the functionality of this tool into a WPS it needs to be able to import it.  Releasing a package to pypi is the solution. Whether or not this means integrating jenkins for automated releases is up for debate.  We may just want to manually release this package.

**Comment by corviday** [comment]
I guess I'd be in favour of setting up automated pushes to pypi.

I frequently make very minor changes to `generate_climos`: I add a new variable and assign it an aggregation method, which is a single line change, every time we start processing a new type of data. Those small changes seem like the sort of things Thunderbird should automatically get; they're not interesting or difficult and don't require any discussion on our part.

**Comment by nikola-rados** [comment]
What has the release schedule looked like for this tool? Would it be possible to push more minor/patch releases since the tool will be used as a package?

**Comment by rod-glover** [comment]
I think automated publishing to PyPI is a good idea. But I'd suggest we stick to our release pattern in other projects; namely, that to publish we tag a commit on master. Slightly more overhead in that it will require updating NEWS and setup.py, but I'd rather do that than have a bunch of undocumented releases (publishes).

@corviday does that work for you? Or are you hoping for something leaner?

**Comment by corviday** [comment]
> What has the release schedule looked like for this tool?

This tool has generally been quite stable, though it is overdue for a release now - looks like I didn't do a release for adding counted, minimum, maximum, and summed variables, and I should have.

**Comment by rod-glover** [comment]
> and I should have

My point exactly. :)

**Comment by nikola-rados** [comment]
Ok, so should I go ahead and implement a pipeline for automated releases (as well as testing)?

**Comment by rod-glover** [comment]
Okay by me.
